mysite/food/urls.py
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
      #food/
      #path('', views.index, name='index'),
      path('', views.IndexClassView.as_view(), name='index'),
      #food/1
      path('<int:pk>/', views.DetailsClassView.as_view(), name='details'),
      # path('<int:item_id>/', views.details, name='details'),
      path('item/', views.item, name='item'),
      #add item
      #path('add', views.create_item, name='create_item'),
      path('add', views.CreateItemView.as_view(), name='create_item'),
      #edit item
      path('update/<int:id>', views.update_item, name='update_item'),
      #delete item
      #path('itemlist/<int:id>', views.delete_item_list, name='delete_item_list'),
      path('delete/<int:id>', views.delete_item, name='delete_item'),
] 

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://t3.ftcdn.net/jpg/02/48/42/64/360_F_248426448_NVKLywWqArG2ADUxDq6QprtIzsF82dMF.jpg")
    #for detail url
    def get_absolute_url(self):
        return reverse("food:details", kwargs={"pk": self.pk})

mysite/food/forms.py
from .models import Item
from django import forms

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    #to retrieve the data from database Item.objects.all()
    item_list = Item.objects.all()
    #templates = loader.get_template('food/index.html') #get template by loader
    context = {
        'item_list':item_list,
    }
    #return HttpResponse(item_list)
    return render(request, 'food/index.html', context)
    #return HttpResponse(templates.render(context, request))

#class based view here...
class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'
    
class DetailsClassView(DetailView):
    model = Item
    template_name = 'food/details.html'
    #context_object_name = 'item'
####################################
def details(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    #return HttpResponse('This is a item no/id: %s' % item_id)
    return render(request, 'food/details.html', context)

def item(request):
   return HttpResponse('This is a Item section view.')

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form':form})

# create item class view...
class CreateItemView(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'
    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request, id):
    item = Item.objects.get(id=id);
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id);

    if request.method=='POST' :
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

# def delete_item_list(request):
#     items = Item.objects.all()
#     context = {
#         'items':items,
#     }
#     return render(request, 'food/delete_item_list.html', context)

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Site</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
    <!--Why need to template? html is a static part of web and database is a dynamic part of web. We would to use combinely through templates in django to built single web page. -->
    <!--NavBar-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
         <a class="navbar-brand" href="{% url 'food:index' %}">FoodApp</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"  aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="main_nav">
           <ul class="navbar-nav">
               <li class="nav-item active"> <a class="nav-link" href="{% url 'food:create_item' %}">Add Item </a> </li>
               <li class="nav-item"><a class="nav-link" href="{% url 'food:index' %}"> View Item </a></li>
               <li class="nav-item"><a class="nav-link" href="#"> Delete Item </a></li>
               {% if user.is_authenticated %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}"> Logout </a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}"> Profile </a></li>
               {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"> Login </a></li>
               {% endif %}
              
           </ul>
         </div> <!-- navbar-collapse.// -->
        </div> <!-- container-fluid.// -->
       </nav>
      <!--End of NavBar-->
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}"> 
              {{ message }}
            </div>
        {% endfor %}
      {% endif %}

       {% block body %}
       {% endblock %}
   
</body>
</html>

mysite/food/templates/food/details.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Site</title>
</head>
<body>
    {% block body %}

    <div class="container my-2 row d-flex justify-content-center" >
        <div class="card mb-3 border-0" style="max-width: 500px;">
            <img src="{{item.item_image}} " height="310px" class="card-img-top" alt="...">
            <div class="card-body">
              <!-- <h4 class="card-title">{{item.item_name}}</h4> -->
              <h4 class="card-title">{{object.item_name}}</h4>
              <h6 class="card-text">{{object.item_desc}}</h6>
              <h5 class="card-text">${{object.item_price}}</h5>
              <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}" role="button">Delete</a>

            </div>
          </div>
    </div>

    {% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Site</title>
   
</head>
<body>

    <!--Django Template Language-->
    {% block body %}

    {% for item in item_list %}
        
        <!-- Old code <ul>
            <li> 
                 <a href="/food/{{item.id}}">{{item.id}} -- {{item.item_name}}</a> 
                <a href="{% url 'food:details' item.id %}">{{item.id}} -- {{item.item_name}}</a>
            </li>
        </ul> {% static 'img/placeholder-image.jpg' %} -->
        <div class="row my-2">
            <div class="col-md-3 offset-md-2">
                <img src=" {{item.item_image}} " height="165px" width="155px" class="card">
            </div>
            <div class="col-md-4">
                <h4>{{item.item_name}}</h4>
                <p>{{item.item_desc}}</p>
                <h6>${{item.item_price}}</h6>
                <h6>${{item.user_name}}</h6>
            </div>
            <div class="col-md-2">
                <a class="btn btn-success mx-1" href="{% url 'food:update_item' item.id %}" role="button">Edit</a>
                <a class="btn btn-success" href="{% url 'food:details' item.id %}" role="button">View</a>
            </div>
        </div>
        
    {% endfor %}

    {% endblock %}

</body>
</html>

mysite/food/templates/food/item-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <h2>Are you sure? you want to delete {{item.item_name}} </h2>
        <button type="submit" class="btn btn-warning">Confirm</button>
        
    </form>
</body>
</html>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Site</title>
</head>
<body>
      
   
    <div class="container my-4">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <h5 class="card-header bg-info">Add Item / Edit</h5>
                    <div class="card-body mx-2">
                        <form class="row" method="post">
                            {% csrf_token %}
                            {{form}}
                            <br>
                            <button type="submit" class="my-2 btn btn-info">Save Item</button>
                        </form>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</body>
</html>

{% endblock %}